[build]
builder = "nixpacks"
buildCommand = "npm run build"

[build.env]
NODE_VERSION = "20.17.0"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"
